### ISSUE TITLE
vim binaries do not exist

### ISSUE THREAD

**Issue by fatih** [macvim-dev/homebrew-macvim#1]
Hi,

After installing this it seems like there are no vim binaries installed:

```
➜  ~  ls /usr/local/Cellar/macvim/HEAD/bin
gview    gvim     gvimdiff gvimex   mview    mvim     mvimdiff mvimex
```

This is why there is no symlink under `/usr/local/bin` for vim:

```
➜  bin git:(master) which mvim
/usr/local/bin/mvim
➜  bin git:(master) which vim
/usr/bin/vim
```

I see that the brew script does it already: https://github.com/macvim-dev/homebrew-macvim/blob/master/macvim.rb#L50, but I wonder why it doesn't produce the binaries. Any thoughts on that?

**Comment by fatih** [comment]
Btw I've just installed it with `brew install vim`. Now I have `vim` and `mvim` both from separate sources though. It doesn't matter of course but just wanted add here in case someone is also having the problem.

**Comment by splhack** [comment]
It actually symlinked `vim` in `bin`.
https://github.com/macvim-dev/homebrew-macvim/blob/a645d0a985e812dd6bfcd20900e122856a1a2218/macvim.rb#L50

So I guess,
1. install vim
2. install macvim, `vim` already exists, brew skipped to create symlink.
3. uninstall vim
4. `vim` doesn't exist

**Comment by fatih** [comment]
I think you didn't read my issue. The problem is not smylinking. The problem is that there are no `vim` binares **produced**. So it doesn't matter if I have vim or not. If you build yourself and cd into `bin` you'll see the binaries don't exist. Am I clear?

**Comment by splhack** [comment]
Yeah, I totally don't understand why you're thinking it is issue. This Homebrew formula doesn't generate any binary files in `/usr/local/Cellar/macvim/HEAD/bin/` and `/usr/local/bin`. The directory does include only symbolic links and `mvim` shell script. The binaries are in `/usr/local/Cellar/macvim/HEAD/MacVim.app/Contents/MacOS`.
