### ISSUE TITLE
Unable to build with homebrew under macOS High Sierra

### ISSUE THREAD

**Issue by cryptoeraser** [macvim-dev/homebrew-macvim#13]
Here is the last part of the log:
[homebrew.log](https://gist.github.com/cryptoeraser/fb4f947a37ff9cc7db275ca0430b5073)

I am trying to build using:
`brew install --HEAD macvim-dev/macvim/macvim --with-properly-linked-python2-python3`

Any ideas?

**Comment by ApolloTang** [comment]
Looks like you are missing commandLineTools... I have similar problem and I have documented my solution here: https://github.com/macvim-dev/macvim/issues/790#issuecomment-444361408

**Comment by ychin** [comment]
Closing. Seems like you don't have command line tools properly set up. You probably want to follow @ApolloTang's instructions
