### ISSUE TITLE
Which formula to use?

### ISSUE THREAD

**Issue by tammersaleh** [macvim-dev/homebrew-macvim#14]
Do we use this one via the custom tap, or [the one found in homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb)?

**Comment by iainjreid** [comment]
This one works perfectly for me, but I'm unable to use the custom tap due to an error that could be related to #9, so I really don't have any choice!

**Comment by ychin** [comment]
Please use the one found in homebrew-core. This repository is not maintained and could be archived in near future. Having one formula is a lot easier to manage and less confusing than two.
