### ISSUE TITLE
which command characters are mappable?

### ISSUE THREAD

**Issue by gartha1** [macvim-dev/homebrew-macvim#15]
hi

which command characters are mappable?

I have installed MacVim with brew, using brew cask install macvim

> ~$ `which vim`
>` /usr/local/bin/vim`
> 

> `~$ cat ~/.vim/vimrc | grep 'D-L'`
> `map <D-L> iabcd`

> ~$vim

I do command-L . and all I get is a beep

If I change the map line to C-L, then Ctrl-L works.

But I want the command key with L..

I try other letters e.g. `map <D-K> iabcd` but no luck

> $ vim --version
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 23:51:40)
> macOS version
> Included patches: 1-950
> Compiled by travis..
> Huge version with MacVim GUI.  Features included (+) or not (-):
> +acl               -farsi             +mouse_sgr         -tag_any_white
>

**Comment by ychin** [comment]
Closing this issue because this is a deprecated repository that isn't actively maintained. Please ask on https://github.com/macvim-dev/macvim if you still have questions.
