### ISSUE TITLE
Failed with brew, but can be done successfully manually?

### ISSUE THREAD

**Issue by bsdcpp** [macvim-dev/homebrew-macvim#16]
I've builded with the latest build tools, got compiled error, and always stuck here like:
```bash
** BUILD FAILED **


The following build commands failed:
	ProcessPCH /tmp/macvim-20201206-27802-n4bext/src/MacVim/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/10866722631058208097/AppKit.h.gch /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2
```

**But** if I come to the tmp dir(with "brew install --keep-tmp --HEAD --with-properly-linked-python2-python3 macvim-dev/macvim/macvim -v"), and type make command, it always turns ok, and can be installed successfully.

My system information:

```
==> Configuration
HOMEBREW_VERSION: 2.6.0-104-g24f7898
ORIGIN: https://github.com/Homebrew/brew
HEAD: 24f7898606b0d41e74fa199032bac7bf97cf91dd
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e75ec6c4f9a9fc728d46dc085cd852ad7d2a91bc
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/lua/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11.0
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gettext/bin:/usr/local/opt/lua/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by bsdcpp** [comment]
At last I made a little trick:
https://github.com/macvim-dev/homebrew-macvim/blob/72aa5a41d89c8e3e35fd9a5f0a7b221e17f73538/macvim.rb#L53
change 
system "make" to system "sleep 120"

then I type make command do it manually.

**Comment by ychin** [comment]
Is there a reason why you are using this tap instead of the official Homebrew formula? This repository has not been actively maintained for years (see README) and I would recommend using the official one instead, but then I'm curious how you  found this to begin with. In fact, I mostly saw this since I was contemplating if I should archive this repository.

**Comment by srihari93** [comment]
> Is there a reason why you are using this tap instead of the official Homebrew formula? This repository has not been actively maintained for years (see README) and I would recommend using the official one instead, but then I'm curious how you found this to begin with. In fact, I mostly saw this since I was contemplating if I should archive this repository.

The wiki https://github.com/macvim-dev/macvim/wiki/Python-2.x-and-Python-3.x leads here, should be taken care of.

> Use the official MacVim Homebrew formula with the option.
>
> $ brew tap macvim-dev/macvim
> $ brew install --HEAD macvim-dev/macvim/macvim --with-properly-linked-python2-python3

**Comment by ychin** [comment]
Ah ok thanks for pointing out. That page is a little old and I can go update it.

That said, Python 2.x is already deprecated though. Is this really an issue (of mixing Python 2/3 plugins)? We could see if we could get this into the homebrew-core formula is there is a need to (otherwise you could manually build MacVim yourself).

**Comment by ychin** [comment]
Closing this out. This repository is not maintained, and there should not be reasons to need Python 2 and 3 interoperability these days anyway as Python 2 has been completely deprecated for a while now.
