### ISSUE TITLE
How do modify macvim before making

### ISSUE THREAD

**Issue by adudek16** [macvim-dev/homebrew-macvim#2]
What is the real difference between using the homebrew tap vs just using the instructions inside the package? 
I need to increase the number of buffers from 4 to 8 or 12 and using the method being recommended doesn't allow for that as far as I can tell.

**Comment by splhack** [comment]
> the instructions inside the package?

What is this?

> I need to increase the number of buffers from 4 to 8 or 12 and using the method being recommended doesn't allow for that as far as I can tell.

I don't get what you want to do. Could you explain more detail?

**Comment by adudek16** [comment]
> >  the instructions inside the package?
> 
> What is this?
> Sorry to be specific, either here which is no longer recommended
> https://github.com/macvim-dev/macvim/wiki/Building-%28not-recommended-way%29
> or README_mac.txt 
> 
> >  I need to increase the number of buffers from 4 to 8 or 12 and using the method being >>recommended doesn't allow for that as far as I can tell.
> 
> I don't get what you want to do. Could you explain more detail?

I want to modify the # define DB_COUNT in structs.h file to be larger then 4 buffers for diff'ing. 

So the question is since the method described in README_mac.txt is no longer recommended and instead we are pushing to use the tap file, how can I use both the tap and modify the code I want?

Why are we no longer recommending using the method described in the README?

**Comment by splhack** [comment]
- clone this repository
- modify macvim.rb to add patch what you want to do https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md
