### ISSUE TITLE
macvim fails to build on 10.11

### ISSUE THREAD

**Issue by flyingglass** [macvim-dev/homebrew-macvim#4]
when i use homebrew to install macvim, it seems to fail. 
1 brew tap macvim-dev/macvim
2 brew install --HEAD macvim-dev/macvim/macvim

the following is my error log:==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/macvim/HEAD --with-features=huge --en
==> make
Last 15 lines from /Users/ly/Library/Logs/Homebrew/macvim/02.make:
1898 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o pl.UTF-8.mo pl.UTF-8.po
1898 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o ru.cp1251.mo ru.cp1251.po
1869 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o sk.cp1250.mo sk.cp1250.po
1869 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o uk.cp1251.mo uk.cp1251.po
1882 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o zh_CN.cp936.mo zh_CN.cp936.po
1628 translated messages.
1883 translated messages.
1633 translated messages, 3 fuzzy translations.
make[2]: Nothing to be done for `converted'.
make: **\* [first] Error 2

READ THIS: https://git.io/brew-troubleshooting

**Comment by splhack** [comment]
I can't repro it and Travis CI works well https://travis-ci.org/macvim-dev/homebrew-macvim/builds/118022854
It's not MacVim Homebrew Tap issue. How about `brew doctor`?

**Comment by flyingglass** [comment]
sorry, it's my mistake
my os is 10.11 but xcode 6.4
thank you all the same

**Comment by flyingglass** [comment]
after update my xcode, it woks well
