### ISSUE TITLE
Fail to install via homebrew

### ISSUE THREAD

**Issue by w3ntao** [macvim-dev/homebrew-macvim#5]
`$ brew install --HEAD macvim-dev/macvim/macvim`

> ==> Installing macvim from macvim-dev/macvim
> ==> Cloning https://github.com/macvim-dev/macvim.git
> Updating /Users/Rahn/Library/Caches/Homebrew/macvim--git
> ==> Checking out branch master
> ==> ./configure --prefix=/usr/local/Cellar/macvim/HEAD-0975715 --with-features=h
> ==> make
> Last 15 lines from /Users/Rahn/Library/Logs/Homebrew/macvim/02.make:
> 1869 translated messages.
> OLD_PO_FILE_INPUT=yes msgfmt -v -o ru.cp1251.mo ru.cp1251.po
> 1869 translated messages.
> OLD_PO_FILE_INPUT=yes msgfmt -v -o sk.cp1250.mo sk.cp1250.po
> 1882 translated messages.
> OLD_PO_FILE_INPUT=yes msgfmt -v -o uk.cp1251.mo uk.cp1251.po
> 1628 translated messages.
> OLD_PO_FILE_INPUT=yes msgfmt -v -o zh_CN.cp936.mo zh_CN.cp936.po
> 1883 translated messages.
> 20 errors generated.
> 1633 translated messages, 3 fuzzy translations.
> make[1]: **\* [objects/os_macosx.o] Error 1
> make[1]: **\* Waiting for unfinished jobs....
> make[2]: Nothing to be done for `converted'.
> make: **\* [first] Error 2

Mac OS X:

> 10.11.6

**Comment by splhack** [comment]
I can't repro it. And Travis-CI builds well.
https://travis-ci.org/macvim-dev/homebrew-macvim/builds/159501522

**Comment by w3ntao** [comment]
Uh, so what additional information I could provide that might be helpful?

**Comment by splhack** [comment]
I strongly recommend you to use binary release https://github.com/macvim-dev/macvim/releases/latest instead of spending time to investigate it. The issue could be anything.
