### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by MacDamien** [macvim-dev/homebrew-macvim#7]
Hi,

When I tried to install Vim :

`MacBook-Pro-de-dv1-2:workspace dv$ brew install --HEAD macvim-dev/macvim/macvim
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
freetype

==> Installing macvim from macvim-dev/macvim
==> Cloning https://github.com/macvim-dev/macvim.git
Updating /Users/dv/Library/Caches/Homebrew/macvim--git
==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/macvim/HEAD-4e631a0 --with-features=h
==> make
Last 15 lines from /Users/dv/Library/Logs/Homebrew/macvim/02.make:
link.sh: OK, linking works, let's try omitting a few libraries.
link.sh: See auto/link.log for details.
link.sh: Trying to omit the iconv library...
link.sh: Vim DOES need the iconv library.
link.sh: Trying to omit the perl library...
link.sh: Vim doesn't need the perl library!
creating auto/pathdef.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/pathdef.o auto/pathdef.c
link.sh: Using auto/link.sed file to omit a few libraries
 env LD_RUN_PATH=/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib 	-o Vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o objects/gui.o objects/gui_beval.o objects/gui_macvim.o objects/MMBackend.o objects/MacVim.o objects/term_encoding.o objects/term_keyboard.o objects/term_mouse.o objects/term_parser.o objects/term_pen.o objects/term_screen.o objects/term_state.o objects/term_unicode.o objects/term_vterm.o objects/if_lua.o  objects/if_perl.o objects/if_perlsfio.o objects/if_python.o objects/if_python3.o  objects/if_ruby.o objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o objects/channel.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -lintl -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
link.sh: Linked fine with a few libraries omitted
xcodebuild -project MacVim/MacVim.xcodeproj MACOSX_DEPLOYMENT_TARGET=10.13 VIM_SHORT_VERSION_STRING=8.0.1428
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make[1]: *** [macvim] Error 1
make: *** [first] Error 2`

What may I do ?

**Comment by oolong32** [comment]
I am getting the same error when trying to install macVim via Homebrew (`brew install --HEAD macvim-dev/macvim/macvim`)on OSX High Sierra:

```
[…]
==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/macvim/HEAD-4e631a0 --with-fe
==> make
Last 15 lines from /Users/josef/Library/Logs/Homebrew/macvim/02.make:
link.sh: OK, linking works, let's try omitting a few libraries.
link.sh: See auto/link.log for details.
link.sh: Trying to omit the iconv library...
link.sh: Vim DOES need the iconv library.
link.sh: Trying to omit the perl library...
link.sh: Vim doesn't need the perl library!
creating auto/pathdef.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/pathdef.o auto/pathdef.c
link.sh: Using auto/link.sed file to omit a few libraries
 env LD_RUN_PATH=/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib    -o Vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o objects/gui.o objects/gui_beval.o objects/gui_macvim.o objects/MMBackend.o objects/MacVim.o objects/term_encoding.o objects/term_keyboard.o objects/term_mouse.o objects/term_parser.o objects/term_pen.o objects/term_screen.o objects/term_state.o objects/term_unicode.o objects/term_vterm.o objects/if_lua.o  objects/if_perl.o objects/if_perlsfio.o objects/if_python.o objects/if_python3.o  objects/if_ruby.o objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o objects/channel.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o -framework Cocoa -framework Carbon
   -lm  -lncurses -liconv -lintl -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
link.sh: Linked fine with a few libraries omitted
xcodebuild -project MacVim/MacVim.xcodeproj MACOSX_DEPLOYMENT_TARGET=10.13 VIM_SHORT_VERSION_STRING=8.0.1428
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make[1]: *** [macvim] Error 1
make: *** [first] Error 2
```

**Comment by pwentz** [comment]
I ran into this error as well (High Sierra). Apparently you have to run the following command in order to point to the actual folder where XCode is installed.
```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
``` 
After that you'll probably have to accept some permissions, which homebrew will notify you about. If you haven't opened Xcode after installing/updating it, then you want to open up Xcode and allow it to install some additional components. After that you shouldn't have any more problems.
