### ISSUE TITLE
Can I build Macvim with RVM Ruby instead of System Ruby

### ISSUE THREAD

**Issue by markwu** [macvim-dev/homebrew-macvim#9]
Here comes with my system versions:

My system is osx `10.13.3`
Homebrew version is `1.5.5-16-g9225dac`
RVM version is `1.29.3`
RVM ruby is `2.5.0p0`
System Ruby is `2.3.3p222`

I want to build macvim with my RVM ruby, but always get system ruby installed.
`:ruby print RUBY_VERSION`
I always get 2.3.3.

Does there any way can let me build macvim with RVM ruby? Thanks!

**Comment by marek-step** [comment]
I am joining this request. I am unable to open .tex files with latex-suite enabled.

System osx: `10.13.4`
Homebrew: `Homebrew 1.6.1`
`Homebrew/homebrew-core (git revision 733efa; last commit 2018-04-20)`

$ `which ruby`
`/usr/local/bin/ruby`
$ `ls -l /usr/local/bin/ruby`
`/usr/local/bin/ruby@ -> ../Cellar/ruby/2.5.1/bin/ruby`

$ `which python`
`/usr/local/bin/python`
$ `ls -l /usr/local/bin/python`
`lrwxr-xr-x  1 mstep  admin  38 15 Apr 21:31 /usr/local/bin/python@ ->`
`../Cellar/python@2/2.7.14_3/bin/python`

In Vim or MacVim: 
`:ruby print RUBY_VERSION`
`2.3.3`

`:python import sys; print(sys.version)`
`2.7.14 (default, Apr 15 2018, 21:28:35)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]`

MacVim and Vim are opening *.txt files without any problem. Trying to open *.tex files I get following error: 

$ `vim neu.tex`
`Vim: Caught deadly signal ABRT`

`Vim: Finished.` 
`Abort trap: 6`

$ `mvim neu.tex`
$ `Fatal Python error: Py_Initialize: unable to load the file system codec`
`ModuleNotFoundError: No module named 'encodings'`

`Current thread 0x00007fffaddcb380 (most recent call first):`
`Vim: Caught deadly signal ABRT`
`Vim: Finished.`

Any hints? I am looking  around for one month now. On ma MacBook vim and MacVim are working with Latex-Suite without any problem. But I am unable to see the difference in the installation. 

Best greetings and Thank you in advance!


marek

**Comment by ychin** [comment]
Are these questions still relevant? This repository is currently unmaintained and you should consider using the official homebrew-core formula.

**Comment by markwu** [comment]
You can use my formula here https://github.com/markwu/homebrew-personal/blob/aa1eb41b305459833789dcfc1ebe95f1d937e1d8/Formula/macvim.rb , it should works for any ruby version.

But, I already used `homebrew-core`'s ruby, instead of RVM's ruby. It makes my life easier.

**Comment by ychin** [comment]
Right. Closing the issue then. I don't remember if you did that or not, but maybe you could file a PR to homebrew-core's MacVim formula to expose that env var as an option.
